### ISSUE TITLE
Event sourcing versioning

### ISSUE THREAD

**Issue by nutshellit** [rommsen/EventSourcing-DIY#1]
Hi Roman, 
I loved the video from F# exchange london from a few weeks ago, thank you for sharing with community.
I appreciate that the code here is a simple demo but perhaps you could give me some pointers on how you approach event versioning assuming that the event is serialized to a datastore and read back at a later date. Any change to the event type will break the deserialisation.
It seems to me that without a strategy to handle this scenario then rolling out changes would be difficult.

**Comment by rommsen** [comment]
Hi @nutshellit, sorry for answering late. Yes event versioning is always a hard topic. There are many ways or strategies to deal with this.
I think you should ask yourself why you need to change the event. Did the business or the requirements change fundamentally? If yes there is no point in changing existing event types. Just create a new type that describes the new requirement and let the old types live forever. I know developers always have the urge to "clean up" and get rid of stuff that is not needed anymore but in those cases in does not make a lot of sense imho. One big point in Event Sourcing is to keep a history of  everything that happened in the business anyway. So if the requirements have been that way at some point in time then let your application reflect that.

If you have just forgotten an information or a property in an event or you want to drop some infos there are many ways to deal with it
* when deserializing fill the new properties with default data if possible or leave some information out (so no auto de-/serialization, need to do it by hand)
* have explicit event versions in you system
* update the event store itself (yes, change your immutable data structure) for example by reading all events, convert them into the new types and storing them into a new store.
* etc.
There is no silver bullet to deal with those problems but you need to think about whats best for your business and your team in certain situations.

Hope this helps a bit.

**Comment by rommsen** [comment]
@nutshellit I am closing this. Feel free to ask follow up question
