### ISSUE TITLE
Use case of event sourcing

### ISSUE THREAD

**Issue by halcwb** [rommsen/EventSourcing-DIY#3]
I am writing a [use case](https://github.com/halcwb/InformedICU) for your event store implementation. I find the whole Event store and CQRS set up fascinating and I think that the setting of a medical application is extremely well suited for such an approach. 

What I first try to do is put the whole app in a script file so I can mess around with it and get a feel of how it works. Only when the app is sufficiently finished I will start to migrate this to a proper project structure.

**Comment by rommsen** [comment]
Cool! Let me now if I can be of any help

**Comment by halcwb** [comment]
@rommsen:
I have a new implementation of your excellent event sourcing setup, with some slight twists. I think it is getting quite nice. I have added versioning of events and explicitly separated the domain modelling from the event sourced infrastructure. I try to follow best practices for domain modelling and event sourcing. Any comments/suggestions are welcome.
