### ISSUE TITLE
Why EventListener and EventStore as a config option

### ISSUE THREAD

**Issue by halcwb** [rommsen/EventSourcing-DIY#5]
The EventListener and EventStore are dependencies for EventSourced. And I know that in principle dependencies should be parameterized. However, it seems quite unlikely to me that these dependencies will quickly change over time or need to be customizable. Also, it makes the config more complex and more difficult to understand. Without them you have a config like:

```
    type EventSourcedConfig<'Comand,'Event,'Query> =
        {
            EventStorageInit : unit -> EventStorage<'Event>
            CommandHandlerInit : EventStore<'Event> -> CommandHandler<'Comand>
            QueryHandler : QueryHandler<'Query>
            EventHandlers : EventHandler<'Event> list
        }

```
Which to me seems more relevant and easier to understand.

See: https://github.com/halcwb/InformedICU/commit/1b7b62d3e294a2163f87d54c16f4ef078dd0887e

**Comment by rommsen** [comment]
It is always a tradeoff. In this case I wanted to have an EventSourced object that has no external dependency. This would allow to switch out parts of the implementation. The whole library could be exported as as dll and it still would be possible to replace the event store or other parts if different needs would arise. 
Possible cases: 
* You want another event store for testing purposes
* You want to wrap the current event store with some kind of caching mechanism. Just wrap the given one in another one that adheres to the interface and you are done.

**Comment by halcwb** [comment]
I get it thanks.
