### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by halcwb** [rommsen/EventSourcing-DIY#7]
I noticed that command handling of a lot of commands (> 1000) at the same time on a stream that contains a large number of events (> 10000) results in poor performance. When running a really large amount of commands, the system gets really slow.

I used this test code:
```

            type Command = HelloWordCommand of string

            type Event = HelloWordEvent of string

            let evs =
                HelloWordEvent "Init"
                |> List.replicate 10000
                |> Event.enveloped "helloworld"

            // create an event store for the hello world event
            let store : EventStore<Event> = 
                EventStorage.InMemoryStorage.initialize evs
                |> EventStore.initialize

            let behaviour : Behaviour<Command, Event> =
                fun cmd ees ->
                    match cmd with
                    | HelloWordCommand s -> 
                        HelloWordEvent s
                        |> List.replicate 2

            let handler =
                initialize behaviour store

            let run n =
                let streamId = "helloworld"
                
                for i in [1..n] do
                    "Hello World"
                    |> HelloWordCommand
                    |> handler.Handle streamId
                    |> Async.RunSynchronously
                    |> ignore

```
If you run 500 times, you'll get:

> run 500;;
> Real: 00:00:06.368, CPU: 00:00:08.218, GC gen0: 425, gen1: 184, gen2: 7
> val it : unit = ()
> 

I also tried this with your demo app, and the same happened. I did not expect this. I thought this would instead be blazing fast as everything runs in memory.

P.S. I know you're code isn't intended as production code, but I am curious. Also, I think F# should have a decent event store library, instead of using a C# based library (ugh ;)).

**Comment by halcwb** [comment]
I did some more research and found that using extensive caching improves performance considerably:

![CachingES](https://user-images.githubusercontent.com/683631/62459919-d6442d80-b780-11e9-9923-1975cc7f35d8.png)

The figure shows the speed up results of subsequent caching of:
- Projections
- List filtering to get the stream

See this [commit](https://github.com/halcwb/InformedICU/tree/2658565886e7e4d2c2062a4469875f2188e57632).

**Comment by halcwb** [comment]
As described in my Projections issue, I completely separated writing and reading. This solved the performance problem! Now it only takes 10 - 20 ms to complete for the whole range of 100 - 2000 commands.

**Comment by rommsen** [comment]
with your caching mechanism you have basically recreated the concepts of readmodels while loosing the ability to reuse your projections for different purposes.

>
> contains a large number of events (> 10000) results
>
I am working with event sourced system for quite some time now and most of the time when I had a single stream with more than 10000 events (so all those events in one aggregate, one specific user, patient, customer etc.) something was modelled fundamentally wrong. Most of the time it was not necessary to load that many events just to be able to process one command.

**Comment by halcwb** [comment]
With regard to performance. The graph I showed was with a far more limited set of events, i.e. an increase with each step of 100. After only 1000 events, it would take 2.6 secs to complete! And 1000 events for a single aggregate seems not unrealistic (take the bank account example). So, this still has me worried.

With regard to caching, is more like memoization. What I figured was that a projection (if it is a pure function), can memoize the result of x events, when x + y events come in, it only has to calculate the y events starting from x. Doesn't it?

Event then, I still cannot understand the performance hit.

**Comment by halcwb** [comment]
And I was probably solving the wrong problem. I tried to solve the problem of too many events  in a stream by improving performance, but instead should look at the aggregate model and try to remodel this such that the number of events is guaranteed to stay limited. 

So, for example your truck that sells flavors and is very successful and sells about 1000 flavors a day and restocks twice a day would generate a lot of events to keep track of, to check the state.  Therefore, you could remodel this to an aggregate that models the daily sales of an truck. This would guarantee that the number of events is limited. A day closed event could then automatically trigger the creation of a new daily sales aggregate with the remaining flavors in stock.

What do you think?
